application:
  assets_bucket: datatools-staging # dist directory
  public_url: http://localhost:8081
  notifications_enabled: false
  port: 4000
  data:
    mapdb: /tmp
    gtfs: /tmp
    editor_mapdb: /tmp
    regions: /tmp
    use_s3_storage: false
    s3_region: us-east-1
    aws_role: arn:aws:iam::${AWS_ACCOUNT_NUMBER}:role/${AWS_ROLE_NAME}
    gtfs_s3_bucket: bucket-name
modules:
  enterprise:
    enabled: false
  editor:
    enabled: true
  user_admin:
    enabled: true
  r5_network:
    enabled: false
  gtfsapi:
    enabled: true
    load_on_fetch: false
    load_on_startup: false
    use_extension: xyz
#    update_frequency: 3600 # in seconds
extensions:
  transitland:
    enabled: true
    api: https://transit.land/api/v1/feeds
  transitfeeds:
    enabled: true
    api: https://api.transitfeeds.com/v1/getFeeds
    key: ${TRANSITFEEDS_API_KEY}