# docker-compose build && docker-compose up

version: "3"

networks:
  napote:

services:
  datatools-ui:
    container_name: datatools-ui
    build:
      context: ./datatools-ui/
    networks:
      - napote
    links:
      - datatools-server
    depends_on:
      - datatools-server

  datatools-server:
    container_name: datatools-server
    build: ./datatools-server/
    environment:
      - MONGO_DATA_DIR=/data/db
    networks:
      - napote
    links:
      - datatools-mongodb:mongo
    depends_on:
      - datatools-mongodb
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"

  datatools-mongodb:
    container_name: datatools-mongodb
    image: mongo:latest
    networks:
      - napote
    ports:
      - "27017:27017"
    command: mongod --smallfiles --dbpath /data/db --nojournal --oplogSize 16 --noauth

  datatools-nginx:
    restart: always
    container_name: datatools-nginx
    build: ./nginx/
    networks:
      - napote
    links:
      - datatools-server
      - datatools-ui
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "8081:8081"
